import {
  AlertTriangle,
  ArrowRight,
  BarChart2,
  Bell,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  Circle,
  Command,
  Copy,
  CreditCard,
  Download,
  File,
  FileText,
  Folder,
  Frame as FrameIcon,
  Github,
  Globe,
  Hash,
  HelpCircle,
  Home,
  Image,
  Laptop,
  LayoutDashboard,
  Link2,
  Loader2,
  LogOut,
  type LucideIcon,
  LucideProps,
  Mail,
  Monitor,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  PlusCircle,
  Search,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Smartphone,
  SunMedium,
  Trash,
  Twitter,
  User,
  User2,
  X,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  logo: FrameIcon,
  spinner: Loader2,
  copy: Copy,
  link: FrameIcon,
  share: Share2,
  check: Check,
  command: Command,
  download: Download,
  hash: Hash,
  barChart: BarChart2,
  user: User,
  user2: User2,
  globe: Globe,
  frame: FrameIcon,
  fileText: FileText,
  file: File,
  folder: Folder,
  image: Image,
  moreVertical: MoreVertical,
  plus: Plus,
  plusCircle: PlusCircle,
  circle: Circle,
  alertTriangle: AlertTriangle,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  gitHub: Github,
  twitter: Twitter,
  link2: Link2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  chevronUpDown: ChevronsUpDown,
  shield: Shield,
  shieldCheck: ShieldCheck,
  bell: Bell,
  home: Home,
  search: Search,
  logout: LogOut,
  arrowRight: ArrowRight,
  mail: Mail,
  layoutDashboard: LayoutDashboard,
  monitor: Monitor,
  smartphone: Smartphone,
  settings: Settings,
  creditCard: CreditCard,
  close: X,
  loading: Loader2,
  trash: Trash,
  google: ({ ...props }: LucideProps) => (
    <svg
      aria-hidden="true"
      focusable="false"
      data-prefix="fab"
      data-icon="google"
      role="img"
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 488 512"
      {...props}
    >
      <path
        fill="currentColor"
        d="M488 261.8C488 403.3 391.1 504 248 504 110.8 504 0 393.2 0 256S110.8 8 248 8c66.8 0 123 24.5 166.3 64.9l-67.5 64.9C258.5 52.6 94.3 116.6 94.3 256c0 86.5 69.1 156.6 153.7 156.6 98.2 0 135-70.4 140.8-106.9H248v-85.3h236.1c2.3 12.7 3.9 24.9 3.9 41.4z"
      />
    </svg>
  ),
} as const;
